package com.aleyon.geminibridge.core;

public final class CoreTests {
    private static int passed=0;
    public static void main(String[] args){testNaming();testRecovery();testSessionReady();testReportParser();testEvidenceGate();testTextDelta();testStaleReportIsolation();testDiagnostics();System.out.println("PASS core tests: "+passed);}
    private static void testNaming(){eq("ALEYON LIVE — Francés — Conversación principal",ProfileNaming.chatName("Francés"));eq("lang-frances",ProfileNaming.profileId("Francés"));eq("lang-portugues-brasil",ProfileNaming.profileId("Portugués Brasil"));ok(ProfileNaming.profileId("日本語").startsWith("lang-u-"));ok(ProfileNaming.isManagedChatName(ProfileNaming.chatName("Italiano")));passed++;}
    private static void testRecovery(){eq(RecoveryPlanner.RecoveryAction.NONE,RecoveryPlanner.plan(SessionStage.READY,false));eq(RecoveryPlanner.RecoveryAction.RESTORE_LIVE_OVERLAY,RecoveryPlanner.plan(SessionStage.LIVE_ACTIVE,true));eq(RecoveryPlanner.RecoveryAction.FINISH_CLOSE,RecoveryPlanner.plan(SessionStage.LIVE_ACTIVE,false));eq(RecoveryPlanner.RecoveryAction.RESTORE_CHAT_OVERLAY,RecoveryPlanner.plan(SessionStage.CHAT_ACTIVE,false));eq(RecoveryPlanner.RecoveryAction.RETRY_START,RecoveryPlanner.plan(SessionStage.CONTEXT_INJECTING,false));passed++;}
    private static void testSessionReady(){String sid="session-123",pid="lang-frances";String okLine=ProtocolContract.SESSION_READY+" SESSION_ID="+sid+" PROFILE_ID="+pid+" SCHEMA_VERSION="+ProtocolContract.SCHEMA_VERSION;ok(SessionReportParser.hasSessionReady("x\n"+okLine+"\ny",sid,pid));ok(!SessionReportParser.hasSessionReady(okLine,sid+"x",pid));passed++;}
    private static void testReportParser(){String sid="session-abc",pid="lang-frances";String t=ProtocolContract.REPORT_BEGIN+" SESSION_ID="+sid+" PROFILE_ID="+pid+" SCHEMA_VERSION="+ProtocolContract.SCHEMA_VERSION+"\nSUMMARY|Buena sesión de conversación.\nNEXT|Practicar pasado.\nFEEDBACK|Sigue respondiendo con frases completas.\nEVENT|grammar|past tense|learning|I goed yesterday\n"+ProtocolContract.REPORT_END+" SESSION_ID="+sid+" PROFILE_ID="+pid;SessionReportParser.Report r=SessionReportParser.parse(t,sid,pid);ok(r!=null);eq("Buena sesión de conversación.",r.summary);eq("Practicar pasado.",r.nextObjective);eq(1,r.events.size());eq("I goed yesterday",r.events.get(0).evidence);passed++;}
    private static void testEvidenceGate(){String sid="session-e",pid="lang-frances";String t=ProtocolContract.REPORT_BEGIN+" SESSION_ID="+sid+" PROFILE_ID="+pid+" SCHEMA_VERSION=3\nEVENT|grammar|past|learning|I goed yesterday\n"+ProtocolContract.REPORT_END+" SESSION_ID="+sid+" PROFILE_ID="+pid;eq(1,SessionReportParser.parse(t,sid,pid,"Alumno: I goed yesterday").events.size());eq(0,SessionReportParser.parse(t,sid,pid,"Alumno: I went yesterday").events.size());passed++;}
    private static void testTextDelta(){String d=SessionTextDelta.delta("A\nB\n","A\nB\nC\nD\n");ok(d.contains("C"));ok(d.contains("D"));ok(!d.contains("A\n"));passed++;}
    private static void testStaleReportIsolation(){String pid="lang-frances",old="old",now="new";String history=ProtocolContract.REPORT_BEGIN+" SESSION_ID="+old+" PROFILE_ID="+pid+" SCHEMA_VERSION=3\nSUMMARY|Viejo\n"+ProtocolContract.REPORT_END+" SESSION_ID="+old+" PROFILE_ID="+pid;ok(SessionReportParser.parse(history,now,pid)==null);ok(SessionReportParser.parse(history,old,pid)!=null);passed++;}
    private static void testDiagnostics(){AutomationDiagnostics d=new AutomationDiagnostics("r","s","b","a",1L,"p",true,2,"sel",0,"ok");ok(d.toJsonString().contains("\"runId\":\"r\""));passed++;}
    private static void ok(boolean x){if(!x)throw new AssertionError("Expected true");}private static void eq(Object a,Object b){if(a==null?b!=null:!a.equals(b))throw new AssertionError("Expected ["+a+"] got ["+b+"]");}
}
